/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.employee;

/**
 *
 * @author TP
 */
public class CalendarView extends javax.swing.JPanel {

    /**
     * Creates new form CalendarView
     */
    public CalendarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        panel_Title = new javax.swing.JPanel();
        label_Title = new javax.swing.JLabel();
        panel_Static = new javax.swing.JPanel();
        panel_FullCalendar = new javax.swing.JPanel();
        panel_Month = new javax.swing.JPanel();
        panel_Day = new javax.swing.JPanel();
        panel_Selection = new javax.swing.JPanel();
        btnEnter = new javax.swing.JButton();
        txtYear = new javax.swing.JTextField();
        cmbMonth = new javax.swing.JComboBox<>();
        panel_DayOfWeek = new javax.swing.JPanel();
        panel_Sunday = new javax.swing.JPanel();
        label_Sunday = new javax.swing.JLabel();
        panel_Monday = new javax.swing.JPanel();
        label_Monday = new javax.swing.JLabel();
        panel_Tuesday = new javax.swing.JPanel();
        label_Tuesday = new javax.swing.JLabel();
        panel_Wednesday = new javax.swing.JPanel();
        label_Wednesday = new javax.swing.JLabel();
        panel_Thursday = new javax.swing.JPanel();
        label_Thursday = new javax.swing.JLabel();
        panel_Friday = new javax.swing.JPanel();
        label_Friday = new javax.swing.JLabel();
        panel_Saturday = new javax.swing.JPanel();
        label_Saturday = new javax.swing.JLabel();

        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(60, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(738, 578));
        setPreferredSize(new java.awt.Dimension(725, 578));
        setLayout(new java.awt.BorderLayout());

        panel_Title.setBackground(new java.awt.Color(255, 255, 153));
        panel_Title.setMaximumSize(new java.awt.Dimension(470, 32));
        panel_Title.setMinimumSize(new java.awt.Dimension(470, 32));
        panel_Title.setPreferredSize(new java.awt.Dimension(470, 32));
        panel_Title.setLayout(new java.awt.GridBagLayout());

        label_Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_Title.setForeground(new java.awt.Color(0, 0, 0));
        label_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Title.setText("Lịch công");
        label_Title.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_Title.add(label_Title, gridBagConstraints);

        add(panel_Title, java.awt.BorderLayout.PAGE_START);

        panel_Static.setBackground(new java.awt.Color(51, 255, 51));
        panel_Static.setAlignmentX(0.0F);
        panel_Static.setAlignmentY(0.0F);
        panel_Static.setMinimumSize(new java.awt.Dimension(255, 500));
        panel_Static.setPreferredSize(new java.awt.Dimension(255, 500));
        add(panel_Static, java.awt.BorderLayout.CENTER);

        panel_FullCalendar.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel_FullCalendar.setMinimumSize(new java.awt.Dimension(60, 70));
        panel_FullCalendar.setPreferredSize(new java.awt.Dimension(470, 512));
        panel_FullCalendar.setLayout(new java.awt.BorderLayout());

        panel_Month.setBackground(new java.awt.Color(204, 209, 209));
        panel_Month.setAlignmentX(0.0F);
        panel_Month.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel_Month.setMinimumSize(new java.awt.Dimension(10, 10));
        panel_Month.setPreferredSize(new java.awt.Dimension(372, 434));
        panel_FullCalendar.add(panel_Month, java.awt.BorderLayout.CENTER);

        panel_Day.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel_Day.setMinimumSize(new java.awt.Dimension(60, 60));
        panel_Day.setPreferredSize(new java.awt.Dimension(483, 79));
        panel_Day.setLayout(new java.awt.BorderLayout());

        panel_Selection.setPreferredSize(new java.awt.Dimension(483, 39));

        btnEnter.setText("Enter");
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMonthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_SelectionLayout = new javax.swing.GroupLayout(panel_Selection);
        panel_Selection.setLayout(panel_SelectionLayout);
        panel_SelectionLayout.setHorizontalGroup(
            panel_SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SelectionLayout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnter)
                .addContainerGap())
        );
        panel_SelectionLayout.setVerticalGroup(
            panel_SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Day.add(panel_Selection, java.awt.BorderLayout.PAGE_START);

        panel_DayOfWeek.setBackground(new java.awt.Color(255, 255, 255));
        panel_DayOfWeek.setAlignmentX(0.0F);
        panel_DayOfWeek.setAlignmentY(0.0F);
        panel_DayOfWeek.setMinimumSize(new java.awt.Dimension(60, 60));
        panel_DayOfWeek.setPreferredSize(new java.awt.Dimension(460, 40));
        panel_DayOfWeek.setRequestFocusEnabled(false);
        panel_DayOfWeek.setVerifyInputWhenFocusTarget(false);

        panel_Sunday.setAlignmentY(0.0F);
        panel_Sunday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Sunday.setText("Chủ nhật");

        javax.swing.GroupLayout panel_SundayLayout = new javax.swing.GroupLayout(panel_Sunday);
        panel_Sunday.setLayout(panel_SundayLayout);
        panel_SundayLayout.setHorizontalGroup(
            panel_SundayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_SundayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_SundayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Sunday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_SundayLayout.setVerticalGroup(
            panel_SundayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_SundayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_SundayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Sunday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Sunday);

        panel_Monday.setAlignmentY(0.0F);
        panel_Monday.setMinimumSize(new java.awt.Dimension(0, 0));
        panel_Monday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Monday.setText("Thứ 2");

        javax.swing.GroupLayout panel_MondayLayout = new javax.swing.GroupLayout(panel_Monday);
        panel_Monday.setLayout(panel_MondayLayout);
        panel_MondayLayout.setHorizontalGroup(
            panel_MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_MondayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Monday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_MondayLayout.setVerticalGroup(
            panel_MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_MondayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Monday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Monday);

        panel_Tuesday.setAlignmentY(0.0F);
        panel_Tuesday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Tuesday.setText("Thứ 3");

        javax.swing.GroupLayout panel_TuesdayLayout = new javax.swing.GroupLayout(panel_Tuesday);
        panel_Tuesday.setLayout(panel_TuesdayLayout);
        panel_TuesdayLayout.setHorizontalGroup(
            panel_TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_TuesdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Tuesday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_TuesdayLayout.setVerticalGroup(
            panel_TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_TuesdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Tuesday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Tuesday);

        panel_Wednesday.setAlignmentY(0.0F);
        panel_Wednesday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Wednesday.setText("Thứ 4");

        javax.swing.GroupLayout panel_WednesdayLayout = new javax.swing.GroupLayout(panel_Wednesday);
        panel_Wednesday.setLayout(panel_WednesdayLayout);
        panel_WednesdayLayout.setHorizontalGroup(
            panel_WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_WednesdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Wednesday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_WednesdayLayout.setVerticalGroup(
            panel_WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_WednesdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Wednesday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Wednesday);

        panel_Thursday.setAlignmentY(0.0F);
        panel_Thursday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Thursday.setText("Thứ 5");

        javax.swing.GroupLayout panel_ThursdayLayout = new javax.swing.GroupLayout(panel_Thursday);
        panel_Thursday.setLayout(panel_ThursdayLayout);
        panel_ThursdayLayout.setHorizontalGroup(
            panel_ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ThursdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Thursday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_ThursdayLayout.setVerticalGroup(
            panel_ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ThursdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Thursday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Thursday);

        panel_Friday.setAlignmentY(0.0F);
        panel_Friday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Friday.setText("Thứ 6");

        javax.swing.GroupLayout panel_FridayLayout = new javax.swing.GroupLayout(panel_Friday);
        panel_Friday.setLayout(panel_FridayLayout);
        panel_FridayLayout.setHorizontalGroup(
            panel_FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_FridayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Friday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_FridayLayout.setVerticalGroup(
            panel_FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_FridayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Friday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Friday);

        panel_Saturday.setAlignmentY(0.0F);
        panel_Saturday.setPreferredSize(new java.awt.Dimension(60, 30));

        label_Saturday.setText("Thứ 7");

        javax.swing.GroupLayout panel_SaturdayLayout = new javax.swing.GroupLayout(panel_Saturday);
        panel_Saturday.setLayout(panel_SaturdayLayout);
        panel_SaturdayLayout.setHorizontalGroup(
            panel_SaturdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(panel_SaturdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_SaturdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Saturday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_SaturdayLayout.setVerticalGroup(
            panel_SaturdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel_SaturdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_SaturdayLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label_Saturday)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_DayOfWeek.add(panel_Saturday);

        panel_Day.add(panel_DayOfWeek, java.awt.BorderLayout.CENTER);

        panel_FullCalendar.add(panel_Day, java.awt.BorderLayout.PAGE_START);

        add(panel_FullCalendar, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterActionPerformed

    private void cmbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Friday;
    private javax.swing.JLabel label_Monday;
    private javax.swing.JLabel label_Saturday;
    private javax.swing.JLabel label_Sunday;
    private javax.swing.JLabel label_Thursday;
    private javax.swing.JLabel label_Title;
    private javax.swing.JLabel label_Tuesday;
    private javax.swing.JLabel label_Wednesday;
    private javax.swing.JPanel panel_Day;
    private javax.swing.JPanel panel_DayOfWeek;
    private javax.swing.JPanel panel_Friday;
    private javax.swing.JPanel panel_FullCalendar;
    private javax.swing.JPanel panel_Monday;
    private javax.swing.JPanel panel_Month;
    private javax.swing.JPanel panel_Saturday;
    private javax.swing.JPanel panel_Selection;
    private javax.swing.JPanel panel_Static;
    private javax.swing.JPanel panel_Sunday;
    private javax.swing.JPanel panel_Thursday;
    private javax.swing.JPanel panel_Title;
    private javax.swing.JPanel panel_Tuesday;
    private javax.swing.JPanel panel_Wednesday;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
