@startuml
package employee {
    class WorkDayInfoController {
        - WorkDayInfoView previousView
        - SimpleDateFormat dateFormat
        - DecimalFormat decimalFormat
        - StatisticalDao statisticalDao
        + void show(WorkDayInfoView view, Calendar calendar, int employeeId) throws Exception
        - String minutesToHours(int m)
    }
    class ChangePasswordController {
        - SuccessCallback sc
        - ErrorCallback ec
        - JFrame previousView
        + void showView()
        + void show(ChangePasswordView view, SuccessCallback sc, ErrorCallback ec)
        - void changePassword(ChangePasswordView view) throws Exception
        + void addEvent()
    }
    class SessionLoginController {
        - SessionLoginView view
        - SimpleDateFormat dateFormatter
        + void render(Session session)
    }
    class LoginHistoryController {
        - JFrame previousView
        - LoginHistoryView view
        - SessionDao sessionDao
        - int employeeId
        + void show(LoginHistoryView view)
        - void render()
    }
    class DayController {
        - DayView view
        - String date
        - int id
        - WorkDayInfoController workDayInfoController
        + DayController(DayView view)
        + DayController(DayView view, String date, int dayNumber, boolean setDay, int id)
        + void addDay(DayView view, int id, Calendar cal, boolean isWorking)
        - void addEvent(DayView view, Calendar cal, int id)
        - void addEvent()
    }
    class CalendarController {
        - CalendarView view
        - int id
        - StatisticalDao statisticalDao
        - WorkingDay workingDay
        - DayController dayController
        - DecimalFormat decimalFormat
        + CalendarController()
        + CalendarController(CalendarView view)
        + void show(JPanel panelRoot, CalendarView view)
        - void renderCalendar(CalendarView view, Calendar cal)
        - void renderStatistical(CalendarView view, Calendar cal)
        - void addEvent(CalendarView view)
    }
    class EmployeeInformationController {
        - Employee sessionEmployee
        - EmployeeInformationView view
        -  ChangePasswordController changePasswordController
        -  LoginHistoryController historyController
        -  CalendarController calendarController
        - void addEvent(EmployeeInformationView view)
        - String secondToHours(int totalSeconds)
    }
}
CalendarController o-- DayController 
DayController o-- WorkDayInfoController
EmployeeInformationController o-- ChangePasswordController
EmployeeInformationController o-- LoginHistoryController
EmployeeInformationController o-- CalendarController
EmployeeInformationController o-- controllers.TimeCounterController
@enduml