@startuml
package views.admin {
    abstract class ManagerPaneView<T extends Model> {

    }
    class AboutView
    class HomeView
    
    class CustomerManagerView {

    }

    class EmployeeManagerView {

    }

    class FoodCategoryManagerView {

    }

    class FoodItemManagerView {

    }

    class OrderManagerView {

    }

    class ShipmentManagerView {

    }

    class TableManagerView {

    }
    class MenuItemView {
    }
}
views.admin.ManagerPaneView --|> javax.swing.JPanel

views.admin.CustomerManagerView --|> views.admin.ManagerPaneView
views.admin.EmployeeManagerView --|> views.admin.ManagerPaneView
views.admin.FoodCategoryManagerView --|> views.admin.ManagerPaneView
views.admin.FoodItemManagerView --|> views.admin.ManagerPaneView
views.admin.OrderManagerView --|> views.admin.ManagerPaneView
views.admin.ShipmentManagerView --|> views.admin.ManagerPaneView
views.admin.TableManagerView --|> views.admin.ManagerPaneView
views.admin.HomeView --|> javax.swing.JPanel
views.admin.AboutView --|> javax.swing.JPanel

views.admin.MenuItemView --|> javax.swing.JPanel
@enduml