@startuml
package views.admin {
    abstract class ManagerPaneView<T extends Model> {
        # DefaultTableModel tableModel
        - ArrayList<T> tableData
        - JButton addButton
        - JComboBox<String> comboSearchField
        - JTable dataTable
        - JButton delButton
        - JButton editButton
        - JTextField searchTxt
        - JButton syncButton
        + int[] getSelectedIds()
        + int getSelectedId()
        + void renderTable()
        + {abstract} void setTableModel()
    }
    class AboutView
    class HomeView
    
    class CustomerManagerView {
        - String list[]
        + void setTableModel()
    }

    class EmployeeManagerView {
        - String list[]
        + void setTableModel()
    }

    class FoodCategoryManagerView {
        - String list[]
        + void setTableModel()
    }

    class FoodItemManagerView {
        - String list[]
        + void setTableModel()
    }

    class OrderManagerView {
        - String list[]
        + void setTableModel()
    }

    class ShipmentManagerView {
        - String list[]
        + void setTableModel()
    }

    class TableManagerView {
        - String list[]
        + void setTableModel()
    }
    class MenuItemView {
        - String id
        - JLabel menuNameLabel
    }
}
views.admin.ManagerPaneView --|> javax.swing.JPanel

views.admin.CustomerManagerView --|> views.admin.ManagerPaneView
views.admin.EmployeeManagerView --|> views.admin.ManagerPaneView
views.admin.FoodCategoryManagerView --|> views.admin.ManagerPaneView
views.admin.FoodItemManagerView --|> views.admin.ManagerPaneView
views.admin.OrderManagerView --|> views.admin.ManagerPaneView
views.admin.ShipmentManagerView --|> views.admin.ManagerPaneView
views.admin.TableManagerView --|> views.admin.ManagerPaneView
views.admin.HomeView --|> javax.swing.JPanel
views.admin.AboutView --|> javax.swing.JPanel

views.admin.MenuItemView --|> javax.swing.JPanel
views.admin.MenuItemView o-- javax.swing.JPanel
@enduml