@startuml
class views.popup.AddOrderPopupView {
    - DefaultComboBoxModel<Table> tbComboBoxModel
}

class views.popup.CustomerPopupView {

}

class views.popup.EditOrderPopupView {
    - DefaultComboBoxModel<Table> tbComboBoxModel
}

class views.popup.EmployeePopupView {

}

class views.popup.FoodCategoryPopupView {
    - JTextField nameTxtField
    - JTextField slugTxtField
    - JButton btnOK
    - JButton btnCancel
}

class views.popup.FoodItemPopupView {
    - DefaultComboBoxModel<FoodCategory> foodCategoryComboBoxModel
}

class views.popup.SelectCustomerPopupView {

}

class views.popup.SelectEmployeePopupView {

}

class views.popup.ShipmentPopupView {

}

class views.popup.TablePopupView {

}

class views.popup.ToppingPopupView {

}

class views.popup.order.FoodCategoryPane {
    - FoodCategory foodCategory
}

class views.popup.order.FoodItemPane {
    - DecimalFormat formatter
    - FoodItem foodItem
}

class views.popup.order.OrderItemPane {
    - OrderItem orderItem
    - DecimalFormat formatter
}
abstract class views.popup.SelectEntityPopupView<T extends Model> {
    # DefaultListModel<T> entityListModel
    + void renderEntity(ArrayList<T> list)
    + void showError(String message)
    + void showError(Exception message)
    + void showMessage(String message)
    # abstract void mineInitComponents()
    # abstract JButton getBtnCancel()
    # abstract JButton getBtnOK()
    # abstract JButton getBtnSearch()
    # abstract JList<T> getEntityList()
    # abstract JTextField getEntityNameTxtField()
}

interface views.popup.BasePopupView {
    + {abstract} JButton getBtnOK()
    + {abstract} JButton getBtnCancel()
}

interface views.popup.BaseSelectEntityPopupView<T extends Model> {
    + {abstract} JButton getBtnSearch();
    + {abstract} JList<T> getEntityList();
    + {abstract} void renderEntity(ArrayList<T> list)
    + {abstract} JTextField getEntityNameTxtField()
}

interface views.popup.MessageShowable {
    + {abstract} void showMessage(String message)
    + {abstract} void showError(String message)
    + {abstract} void showError(Exception e)
}

interface views.popup.PopupView {
    + {abstract} JLabel getLbTitle()
    + {abstract} void dispose()
    + {abstract} void setVisible(boolean b)
    + {abstract} String getClassName()
}
views.popup.AddOrderPopupView --|> java.swing.JFrame
views.popup.CustomerPopupView --|> java.swing.JFrame
views.popup.EditOrderPopupView --|> java.swing.JFrame
views.popup.EmployeePopupView --|> java.swing.JFrame
views.popup.FoodCategoryPopupView --|> java.swing.JFrame
views.popup.FoodItemPopupView --|> java.swing.JFrame
views.popup.ShipmentPopupView --|> java.swing.JFrame
views.popup.TablePopupView --|> java.swing.JFrame
views.popup.ToppingPopupView --|> java.swing.JFrame
views.popup.order.FoodCategoryPane --|> java.swing.JPanel
views.popup.order.FoodItemPane --|> java.swing.JPanel
views.popup.order.OrderItemPane --|> java.swing.JPanel
views.popup.SelectEntityPopupView --|> java.swing.JFrame
views.popup.ToppingPopupView --|> java.swing.JFrame
views.popup.ToppingPopupView --|> java.swing.JFrame

views.popup.PopupView ..|> views.popup.BasePopupView
views.popup.BasePopupView ..|> views.popup.MessageShowable
views.popup.SelectEntityPopupView ..|> views.popup.BaseSelectEntityPopupView
views.popup.AddOrderPopupView ..|> views.popup.PopupView
views.popup.CustomerPopupView ..|> views.popup.PopupView
views.popup.EditOrderPopupView ..|> views.popup.PopupView
views.popup.EmployeePopupView ..|> views.popup.PopupView
views.popup.FoodCategoryPopupView ..|> views.popup.PopupView
views.popup.FoodItemPopupView ..|> views.popup.PopupView
views.popup.TablePopupView ..|> views.popup.PopupView
views.popup.ToppingPopupView ..|> views.popup.PopupView
views.popup.SelectCustomerPopupView --|> views.popup.SelectEntityPopupView
views.popup.SelectEmployeePopupView --|> views.popup.SelectEntityPopupView
views.popup.ShipmentPopupView ..|> views.popup.PopupView
views.popup.BaseSelectEntityPopupView ..|> views.popup.MessageShowable

@enduml