@startuml
class views.popup.AddOrderPopupView {
}

class views.popup.CustomerPopupView {

}

class views.popup.EditOrderPopupView {

}

class views.popup.EmployeePopupView {

}

class views.popup.FoodCategoryPopupView {
}

class views.popup.FoodItemPopupView {
}

class views.popup.SelectCustomerPopupView {

}

class views.popup.SelectEmployeePopupView {

}

class views.popup.ShipmentPopupView {

}

class views.popup.TablePopupView {

}

class views.popup.ToppingPopupView {
}

class views.popup.order.FoodCategoryPane {
}

class views.popup.order.FoodItemPane {

}

class views.popup.order.OrderItemPane {

}
abstract class views.popup.SelectEntityPopupView<T extends Model> {

}

interface views.popup.BasePopupView {

}

interface views.popup.BaseSelectEntityPopupView<T extends Model> {

}

interface views.popup.MessageShowable {

}

interface views.popup.PopupView {

}
views.popup.AddOrderPopupView --|> java.swing.JFrame
views.popup.CustomerPopupView --|> java.swing.JFrame
views.popup.EditOrderPopupView --|> java.swing.JFrame
views.popup.EmployeePopupView --|> java.swing.JFrame
views.popup.FoodCategoryPopupView --|> java.swing.JFrame
views.popup.FoodItemPopupView --|> java.swing.JFrame
views.popup.ShipmentPopupView --|> java.swing.JFrame
views.popup.TablePopupView --|> java.swing.JFrame
views.popup.ToppingPopupView --|> java.swing.JFrame
views.popup.order.FoodCategoryPane --|> java.swing.JPanel
views.popup.order.FoodItemPane --|> java.swing.JPanel
views.popup.order.OrderItemPane --|> java.swing.JPanel
views.popup.SelectEntityPopupView --|> java.swing.JFrame
views.popup.ToppingPopupView --|> java.swing.JFrame
views.popup.ToppingPopupView --|> java.swing.JFrame

views.popup.PopupView ..|> views.popup.BasePopupView
views.popup.BasePopupView ..|> views.popup.MessageShowable
views.popup.SelectEntityPopupView ..|> views.popup.BaseSelectEntityPopupView
views.popup.AddOrderPopupView ..|> views.popup.PopupView
views.popup.CustomerPopupView ..|> views.popup.PopupView
views.popup.EditOrderPopupView ..|> views.popup.PopupView
views.popup.EmployeePopupView ..|> views.popup.PopupView
views.popup.FoodCategoryPopupView ..|> views.popup.PopupView
views.popup.FoodItemPopupView ..|> views.popup.PopupView
views.popup.TablePopupView ..|> views.popup.PopupView
views.popup.ToppingPopupView ..|> views.popup.PopupView
views.popup.SelectCustomerPopupView --|> views.popup.SelectEntityPopupView
views.popup.SelectEmployeePopupView --|> views.popup.SelectEntityPopupView
views.popup.ShipmentPopupView ..|> views.popup.PopupView
views.popup.BaseSelectEntityPopupView ..|> views.popup.MessageShowable

@enduml