@startuml
package views.employee {
    class EmployeeInformationView {
        - JPanel calendarPanel
        - JButton changePassButton
        - JButton historySessionButton
        - JLabel timeSessionLabel
    }

    class WorkDayInfoView 
    class LoginHistoryView
    class DayView
    class SessionLoginView
    class CalendarView{
        - JPanel panelTitle
        - JPanel panelStatic
        - JPanel panelTotalBills
        - JPanel panelTotalSales
        - JPanel panelTotalWorkingTime
        - JPanel panelTotalBonus
        - JPanel panelTotalWorkingDays
        - JPanel panelFullCalendar
        - JPanel panelMonth
        - JPanel panelDay
    }
}

class javax.swing.JPanel

views.employee.EmployeeInformationView --|> javax.swing.JPanel
views.employee.WorkDayInfoView --|> javax.swing.JFrame
views.employee.LoginHistoryView --|> javax.swing.JFrame
views.employee.SessionLoginView --|> javax.swing.JPanel
views.employee.DayView --|> javax.swing.JPanel
views.employee.CalendarView --|> javax.swing.JPanel




views.employee.EmployeeInformationView o-- javax.swing.JPanel

views.employee.WorkDayInfoView o-- javax.swing.JPanel
@enduml